language: python

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/download
python:
  - "2.7"
  - "3.6"
install:
  - echo "Should be handled by setuptools"
script:
  - python setup.py test
